.class public Lcom/android/settings/Settings;
.super Lcom/android/settings/SettingsActivity;
.source "Settings.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/android/settings/Settings$LockscreenNotificationActivity;,
        Lcom/android/settings/Settings$SystemDashboardActivity;,
        Lcom/android/settings/Settings$AccountDashboardActivity;,
        Lcom/android/settings/Settings$StorageDashboardActivity;,
        Lcom/android/settings/Settings$AppAndNotificationDashboardActivity;,
        Lcom/android/settings/Settings$PowerUsageSummaryActivity;,
        Lcom/android/settings/Settings$ConnectedDeviceDashboardActivity;,
        Lcom/android/settings/Settings$NetworkDashboardActivity;,
        Lcom/android/settings/Settings$AdvancedConnectedDeviceActivity;,
        Lcom/android/settings/Settings$WebViewAppPickerActivity;,
        Lcom/android/settings/Settings$EnterprisePrivacySettingsActivity;,
        Lcom/android/settings/Settings$WifiInfoActivity;,
        Lcom/android/settings/Settings$WifiAPITestActivity;,
        Lcom/android/settings/Settings$TestingSettingsActivity;,
        Lcom/android/settings/Settings$IccLockSettingsActivity;,
        Lcom/android/settings/Settings$ChooseAccountActivity;,
        Lcom/android/settings/Settings$ApnEditorActivity;,
        Lcom/android/settings/Settings$ManagedProfileSettingsActivity;,
        Lcom/android/settings/Settings$WallpaperSettingsActivity;,
        Lcom/android/settings/Settings$ManageAppExternalSourcesActivity;,
        Lcom/android/settings/Settings$ManageExternalSourcesActivity;,
        Lcom/android/settings/Settings$SecDisabledAppsActivity;,
        Lcom/android/settings/Settings$AdvancedAppsActivity;,
        Lcom/android/settings/Settings$AppWriteSettingsActivity;,
        Lcom/android/settings/Settings$AppDrawOverlaySettingsActivity;,
        Lcom/android/settings/Settings$ChangeWifiStateActivity;,
        Lcom/android/settings/Settings$WriteSettingsActivity;,
        Lcom/android/settings/Settings$OverlaySettingsActivity;,
        Lcom/android/settings/Settings$AppMemoryUsageActivity;,
        Lcom/android/settings/Settings$MemorySettingsActivity;,
        Lcom/android/settings/Settings$WifiCallingSettingsActivity;,
        Lcom/android/settings/Settings$ApnSettingsActivity;,
        Lcom/android/settings/Settings$DirectoryAccessSettingsActivity;,
        Lcom/android/settings/Settings$PhotosStorageActivity;,
        Lcom/android/settings/Settings$MoviesStorageActivity;,
        Lcom/android/settings/Settings$GamesStorageActivity;,
        Lcom/android/settings/Settings$AutomaticStorageManagerSettingsActivity;,
        Lcom/android/settings/Settings$ManageDomainUrlsActivity;,
        Lcom/android/settings/Settings$ChannelGroupNotificationSettingsActivity;,
        Lcom/android/settings/Settings$ChannelNotificationSettingsActivity;,
        Lcom/android/settings/Settings$AppNotificationSettingsActivity;,
        Lcom/android/settings/Settings$NotificationAppListActivity;,
        Lcom/android/settings/Settings$ConfigureNotificationSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeEventRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeScheduleRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeAutomationSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeBlockedEffectsSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeBehaviorSettingsActivity;,
        Lcom/android/settings/Settings$PrintJobSettingsActivity;,
        Lcom/android/settings/Settings$PrintSettingsActivity;,
        Lcom/android/settings/Settings$PaymentDCMSettingsActivity;,
        Lcom/android/settings/Settings$PaymentSettingsActivity;,
        Lcom/android/settings/Settings$UserCredentialsSettingsActivity;,
        Lcom/android/settings/Settings$TrustedCredentialsSettingsActivity;,
        Lcom/android/settings/Settings$UsbDetailsActivity;,
        Lcom/android/settings/Settings$ZenAccessSettingsActivity;,
        Lcom/android/settings/Settings$AppPictureInPictureSettingsActivity;,
        Lcom/android/settings/Settings$PictureInPictureSettingsActivity;,
        Lcom/android/settings/Settings$VrListenersSettingsActivity;,
        Lcom/android/settings/Settings$NotificationAccessSettingsActivity;,
        Lcom/android/settings/Settings$UserSettingsActivity;,
        Lcom/android/settings/Settings$NotificationStationActivity;,
        Lcom/android/settings/Settings$DreamSettingsActivity;,
        Lcom/android/settings/Settings$WifiDisplaySettingsActivity;,
        Lcom/android/settings/Settings$AndroidBeamSettingsActivity;,
        Lcom/android/settings/Settings$TextToSpeechSettingsActivity;,
        Lcom/android/settings/Settings$SavedAccessPointsSettingsActivity;,
        Lcom/android/settings/Settings$WifiControlHistoryActivity;,
        Lcom/android/settings/Settings$ConfigureWifiSettingsActivity;,
        Lcom/android/settings/Settings$MobileDataUsageListActivity;,
        Lcom/android/settings/Settings$WifiNetworkDetailsActivity;,
        Lcom/android/settings/Settings$WifiModifyActivity;,
        Lcom/android/settings/Settings$WifiManageNetworkActivity;,
        Lcom/android/settings/Settings$WifiAdvancedActivity;,
        Lcom/android/settings/Settings$WifiAddNetworkActivity;,
        Lcom/android/settings/Settings$WifiNetworkConnectActivity;,
        Lcom/android/settings/Settings$MobileDataOnlyActivity;,
        Lcom/android/settings/Settings$DataUsageSummaryLegacyActivity;,
        Lcom/android/settings/Settings$DataUsageSummaryCHNActivity;,
        Lcom/android/settings/Settings$DataUsageSummaryActivity;,
        Lcom/android/settings/Settings$DeviceAdminSettingsActivity;,
        Lcom/android/settings/Settings$CryptKeeperSettingsActivity;,
        Lcom/android/settings/Settings$AccountSyncSettingsActivity;,
        Lcom/android/settings/Settings$BatterySaverSettingsActivity;,
        Lcom/android/settings/Settings$RunningServicesActivity;,
        Lcom/android/settings/Settings$PrivacySettingsActivity;,
        Lcom/android/settings/Settings$ScanningSettingsActivity;,
        Lcom/android/settings/Settings$LocationCmccAgpsActivity;,
        Lcom/android/settings/Settings$LocationSettingsActivity;,
        Lcom/android/settings/Settings$UsageAccessSettingsActivity;,
        Lcom/android/settings/Settings$SecurityDashboardActivity;,
        Lcom/android/settings/Settings$AccessibilityDaltonizerSettingsActivity;,
        Lcom/android/settings/Settings$CaptioningSettingsActivity;,
        Lcom/android/settings/Settings$AccessibilityInstalledServiceActivity;,
        Lcom/android/settings/Settings$AccessibilitySettingsActivity;,
        Lcom/android/settings/Settings$DirectionLockSplashActivity;,
        Lcom/android/settings/Settings$DevelopmentSettingsDashboardActivity;,
        Lcom/android/settings/Settings$StorageUseActivity;,
        Lcom/android/settings/Settings$BackgroundCheckSummaryActivity;,
        Lcom/android/settings/Settings$HighPowerApplicationsActivity;,
        Lcom/android/settings/Settings$ManageAssistActivity;,
        Lcom/android/settings/Settings$ManageApplicationsActivity;,
        Lcom/android/settings/Settings$MyDeviceInfoActivity;,
        Lcom/android/settings/Settings$DeviceInfoSettingsActivity;,
        Lcom/android/settings/Settings$NightDisplaySuggestionActivity;,
        Lcom/android/settings/Settings$NightDisplaySettingsActivity;,
        Lcom/android/settings/Settings$DisplaySettingsActivity;,
        Lcom/android/settings/Settings$UserDictionarySettingsActivity;,
        Lcom/android/settings/Settings$LanguageAndInputSettingsActivity;,
        Lcom/android/settings/Settings$LocalePickerActivity;,
        Lcom/android/settings/Settings$SpellCheckersSettingsActivity;,
        Lcom/android/settings/Settings$DefaultAutofillPickerActivity;,
        Lcom/android/settings/Settings$VirtualKeyboardActivity;,
        Lcom/android/settings/Settings$PhysicalKeyboardActivity;,
        Lcom/android/settings/Settings$KeyboardLayoutPickerActivity;,
        Lcom/android/settings/Settings$AvailableVirtualKeyboardActivity;,
        Lcom/android/settings/Settings$WifiP2pSettingsActivity;,
        Lcom/android/settings/Settings$WifiSettingsActivity;,
        Lcom/android/settings/Settings$SmartTetherSettingsActivity;,
        Lcom/android/settings/Settings$WifiApSettingsActivity;,
        Lcom/android/settings/Settings$PublicVolumeSettingsActivity;,
        Lcom/android/settings/Settings$PrivateVolumeSettingsActivity;,
        Lcom/android/settings/Settings$PrivateVolumeForgetActivity;,
        Lcom/android/settings/Settings$DateTimeSettingsActivity;,
        Lcom/android/settings/Settings$VpnSettingsActivity;,
        Lcom/android/settings/Settings$TetherSettingsActivity;,
        Lcom/android/settings/Settings$SimSettingsActivity;,
        Lcom/android/settings/Settings$BluetoothSettingsActivity;,
        Lcom/android/settings/Settings$AssistGestureSettingsActivity;,
        Lcom/android/settings/Settings$BtTetherSettingsActivity;,
        Lcom/android/settings/Settings$BluetoothControlHistoryActivity;,
        Lcom/android/settings/Settings$BluetoothDualPlaySettingsActivity;,
        Lcom/android/settings/Settings$BluetoothAVCSettingsActivity;,
        Lcom/android/settings/Settings$BluetoothAdvancedSettingsActivity;,
        Lcom/android/settings/Settings$DeviceProfilesSettingsActivity;,
        Lcom/android/settings/Settings$SimLockStatusActivity;,
        Lcom/android/settings/Settings$ImeiInformationActivity;,
        Lcom/android/settings/Settings$SimStatusActivity;,
        Lcom/android/settings/Settings$StatusActivity;,
        Lcom/android/settings/Settings$SoftwareInformationActivity;,
        Lcom/android/settings/Settings$LegalInformationActivity;,
        Lcom/android/settings/Settings$FOTASuggestionActivity;,
        Lcom/android/settings/Settings$SoftwareUpdateSettingActivity;,
        Lcom/android/settings/Settings$BlockNotificationListActivity;,
        Lcom/android/settings/Settings$LockscreenSettingsActivity;,
        Lcom/android/settings/Settings$MotionAndGestureSettingsActivity;,
        Lcom/android/settings/Settings$FingerSensorGestureSettinsActivity;,
        Lcom/android/settings/Settings$HDReffectSettinsActivity;,
        Lcom/android/settings/Settings$MotionAndGestureActivity;,
        Lcom/android/settings/Settings$UsefulFeatureActivity;,
        Lcom/android/settings/Settings$OnehandOperationSettingsActivity;,
        Lcom/android/settings/Settings$SmartStaySettingsActivity;,
        Lcom/android/settings/Settings$ShowInformationActivity;,
        Lcom/android/settings/Settings$DockSettingsActivity;,
        Lcom/android/settings/Settings$ActiveKeySettingsActivity;,
        Lcom/android/settings/Settings$UsefulFeatureMainActivity;,
        Lcom/android/settings/Settings$RegisterIrisSettingsActivity;,
        Lcom/android/settings/Settings$RegisterFingerprintSettingsActivity;,
        Lcom/android/settings/Settings$RegisterFaceSettingsActivity;,
        Lcom/android/settings/Settings$RegisterIntelligentScanSettingsActivity;,
        Lcom/android/settings/Settings$IrisSettingsActivity;,
        Lcom/android/settings/Settings$SmartScanSettingsActivity;,
        Lcom/android/settings/Settings$FindMyMobileSettingsActivity;,
        Lcom/android/settings/Settings$FaceSettingsActivity;,
        Lcom/android/settings/Settings$FingerprintSettingsActivity;,
        Lcom/android/settings/Settings$StrongProtectionSettingsActivity;,
        Lcom/android/settings/Settings$CryptSDCardSettingsActivity;,
        Lcom/android/settings/Settings$BiometricsAndSecuritySettingsActivity;,
        Lcom/android/settings/Settings$HelpActivity;,
        Lcom/android/settings/Settings$HomeSettingsActivity;,
        Lcom/android/settings/Settings$DCMHomeSettingsActivity;,
        Lcom/android/settings/Settings$AllApplicationsActivity;,
        Lcom/android/settings/Settings$SecAdaptiveDisplaySettingsActivity;,
        Lcom/android/settings/Settings$ScreenTimeoutActivity;,
        Lcom/android/settings/Settings$NewModePreviewActivity;,
        Lcom/android/settings/Settings$SecScreenSizeActivity;,
        Lcom/android/settings/Settings$SecFontStyleActivity;,
        Lcom/android/settings/Settings$SecFontSizeActivity;,
        Lcom/android/settings/Settings$AutoBrightnessActivity;,
        Lcom/android/settings/Settings$NavigationBarHideButtonAppsSettingsActivity;,
        Lcom/android/settings/Settings$NavigationBarHardPressSettingsActivity;,
        Lcom/android/settings/Settings$NavigationBarSettingsActivity;,
        Lcom/android/settings/Settings$EasyModeAppActivity;,
        Lcom/android/settings/Settings$FullScreenAppsSettingsActivity;,
        Lcom/android/settings/Settings$LaunchDisplaySettingsActivity;,
        Lcom/android/settings/Settings$StatusBarActivity;,
        Lcom/android/settings/Settings$NightThemeSettingsInnerActivity;,
        Lcom/android/settings/Settings$NightThemeSettingsActivity;,
        Lcom/android/settings/Settings$BlueLightFilterSettingsActivity;,
        Lcom/android/settings/Settings$CloudAccountSettingsActivity;,
        Lcom/android/settings/Settings$BadgeAppIconSettingsActivity;,
        Lcom/android/settings/Settings$SecZenModeDNDSettingsInnerActivity;,
        Lcom/android/settings/Settings$SecZenModeDNDSettingsActivity;,
        Lcom/android/settings/Settings$SecVolumeLimiterSettingsActivity;,
        Lcom/android/settings/Settings$SecVolumeSettingsActivity;,
        Lcom/android/settings/Settings$SecSoundModeSettingsActivity;,
        Lcom/android/settings/Settings$SoundSettingsActivity;,
        Lcom/android/settings/Settings$MasterClearActivity;,
        Lcom/android/settings/Settings$ResetSettingsActivity;,
        Lcom/android/settings/Settings$ResetNetworkActivity;,
        Lcom/android/settings/Settings$ResetDashboardFragmentActivity;,
        Lcom/android/settings/Settings$GeneralDeviceSettingsActivity;,
        Lcom/android/settings/Settings$NfcAdvancedRoutingSettingActivity;,
        Lcom/android/settings/Settings$NfcOsaifukeitaiSettingsActivity;,
        Lcom/android/settings/Settings$NfcSettingsActivity;,
        Lcom/android/settings/Settings$DeviceVisibilitySettingsActivity;,
        Lcom/android/settings/Settings$WirelessSettingsActivity;,
        Lcom/android/settings/Settings$GigaMultiPathActivity;,
        Lcom/android/settings/Settings$EthernetSettingsActivity;,
        Lcom/android/settings/Settings$DomesticSettingsActivity;,
        Lcom/android/settings/Settings$TRoamingSettingsActivity;,
        Lcom/android/settings/Settings$LGTRoamingEnv;,
        Lcom/android/settings/Settings$GlobalRoamingSettingsActivity;,
        Lcom/android/settings/Settings$AirplaneModeSettingsActivity;,
        Lcom/android/settings/Settings$ConnectionsSettingsActivity;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Lcom/android/settings/SettingsActivity;-><init>()V

    return-void
.end method


# virtual methods
.method public onPause()V
    .locals 0

    invoke-super {p0}, Lcom/android/settings/SettingsActivity;->onPause()V

    invoke-virtual {p0}, Lcom/android/settings/Settings;->unregisterAssistant()V

    return-void
.end method

.method public onResume()V
    .locals 0

    invoke-super {p0}, Lcom/android/settings/SettingsActivity;->onResume()V

    invoke-virtual {p0}, Lcom/android/settings/Settings;->registerAssistant()V

    return-void
.end method
